name: Dragon
version: 1.0
api-version: 1.18
main: me.yujiro.dragon.Dragon
depend: [ProjectKorra]
authors: [Yujiro]
description: Adds Ozai style abilities
dragon.player:
    default: true
    description: Access to dragon abilities.
    children:
      bending.ability.DragonsBreath: true
      bending.ability.DragonsJet: true
      bending.ability.DragonsComet: true
      bending.ability.DragonsScales: true
      bending.ability.DragonsBolt: true
      bending.ability.DragonsSlam: true